name: ifn_app_mvp
description: Indie Film Network - Connecting filmmakers and embracing AI innovation.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6
  
  # Backend & Authentication
  supabase_flutter: ^1.10.4
  
  # UI Components
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.2.3
  
  # Location Services
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  
  # Storage & Local Data
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  file_picker: ^5.3.1
  connectivity_plus: ^4.0.1
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
